/*
* 文 件 名:  UserRole.java
* 版     权:  百立特信息技术有限公司
* 描     述:  数据库实体类:UserRole
* 修 改 人:  teng
* 修改时间:  2019年07月16日
* 修改内容:  <修改内容>
*/
package com.forum.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class UserRole implements Serializable {
    /**
     * 用户和角色关联表
     */
    private Long pkUserId;

    /**
     * 用户id
     */
    private Long fkUserId;

    /**
     * 角色id
     */
    private Long fkRoleId;

    /**
     * 创建时间
     */
    private Date createdTime;

    /**
     * 更新时间
     */
    private Date updatedTime;

    /**
     * 假删除 0：未删除，1：已删除
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    private static final long serialVersionUID = 1L;

    public Long getPkUserId() {
        return pkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.pk_user_id
     *
     * @param pkUserId the value for user_role.pk_user_id
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    public void setPkUserId(Long pkUserId) {
        this.pkUserId = pkUserId;
    }

    public Long getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.fk_user_id
     *
     * @param fkUserId the value for user_role.fk_user_id
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    public void setFkUserId(Long fkUserId) {
        this.fkUserId = fkUserId;
    }

    public Long getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.fk_role_id
     *
     * @param fkRoleId the value for user_role.fk_role_id
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    public void setFkRoleId(Long fkRoleId) {
        this.fkRoleId = fkRoleId;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.CREATED_TIME
     *
     * @param createdTime the value for user_role.CREATED_TIME
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.UPDATED_TIME
     *
     * @param updatedTime the value for user_role.UPDATED_TIME
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.is_del
     *
     * @param isDel the value for user_role.is_del
     *
     * @mbggenerated Tue Jul 16 20:01:12 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}