/*
* 文 件 名:  UserRoleRelevance.java
* 版     权:  百立特信息技术有限公司
* 描     述:  数据库实体类:UserRoleRelevance
* 修 改 人:  teng
* 修改时间:  2019年11月07日
* 修改内容:  <修改内容>
*/
package com.forum.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class UserRoleRelevance implements Serializable {
    /**
     * 用户和角色关联表
     */
    private Long pkUserRoleRelevanceId;

    /**
     * 用户id
     */
    private Long fkUserId;

    /**
     * 角色id
     */
    private Long fkRoleId;

    /**
     * 创建时间
     */
    private Date createdTime;

    /**
     * 更新时间
     */
    private Date updatedTime;

    /**
     * 假删除 0：未删除，1：已删除
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role_relevance
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    public Long getPkUserRoleRelevanceId() {
        return pkUserRoleRelevanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relevance.pk_user_role_relevance_id
     *
     * @param pkUserRoleRelevanceId the value for user_role_relevance.pk_user_role_relevance_id
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    public void setPkUserRoleRelevanceId(Long pkUserRoleRelevanceId) {
        this.pkUserRoleRelevanceId = pkUserRoleRelevanceId;
    }

    public Long getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relevance.fk_user_id
     *
     * @param fkUserId the value for user_role_relevance.fk_user_id
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    public void setFkUserId(Long fkUserId) {
        this.fkUserId = fkUserId;
    }

    public Long getFkRoleId() {
        return fkRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relevance.fk_role_id
     *
     * @param fkRoleId the value for user_role_relevance.fk_role_id
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    public void setFkRoleId(Long fkRoleId) {
        this.fkRoleId = fkRoleId;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relevance.CREATED_TIME
     *
     * @param createdTime the value for user_role_relevance.CREATED_TIME
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relevance.UPDATED_TIME
     *
     * @param updatedTime the value for user_role_relevance.UPDATED_TIME
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relevance.is_del
     *
     * @param isDel the value for user_role_relevance.is_del
     *
     * @mbggenerated Thu Nov 07 14:22:17 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}